---
title: Project Design Review Presentation Specs
format:
  html: default
  pdf: default
---

The purpose of the design review presentation is to provide you with the opportunity to share the plan for your project with your classmates and solicit their feedback. 

You are free to structure your presentation however you would like, but most successful presentations include the following components.

- Introduction: introduce the problem statement and the objectives of the project. What are you trying to achieve? What inspired you to choose this project?
- Specifications: What will your project do?
- Implementation: Present a block diagram of your system.
  - What is the role of the MCU and the FPGA? 
  - What new hardware are you using? 
  - What new MCU peripheral(s) are you planning to use?
- Feedback: Solicit feedback from your peers. This requires some thought and intentionality do well. The goal of this section is to solicit feedback on a technical topic, not just on a high-level implementation detail (e.g., what color to paint the box) Some ideas to consider:
  - What technical problem would you like to receive feedback on from your peers?
  - How would you like them to provide feedback?
- Conclusion and Q&A: Briefly conclude the presentation and field questions from the audience (as time allows)

The specifications below lay out how you will be assessed.

## Proficiency

- [ ] Presentation gives overview of the project
- [ ] Presentation presents a problem or question for the class
- [ ] Input solicited from the class

## Excellence

- [ ] Presentation wraps up on time
- [ ] Slides are well formatted with no spelling, grammar, or formatting issues.
- [ ] Presentation presents an in-depth technical problem
- [ ] Problem or question for the class is technical in nature (e.g., soliciting feedback about tradeoffs for a specific protocol for an interface).