---
title: "Resources"
---

# E155 FA22 Development Board
* [E155 Development Board Schematic](/assets/doc/E155 Development Board Schematic.pdf)
* [E155 Breadboard Adapter Schematic](/assets/doc/E155 Breadboard Adapter Schematic.pdf)
* [E155 Development Board BOM](/assets/doc/E155_FA23_Dev_Board_BOM.html)

# Nucleo & STM32 Documentation
* [STM32L432KC Datasheet](/assets/doc/ds11451-stm32l432kc.pdf)
* [STM32L432KC Reference Manual](/assets/doc/rm0394-stm32l41xxx42xxx43xxx44xxx45xxx46xxx-advanced-armbased-32bit-mcus-stmicroelectronics.pdf)
* [STM32L432KC Programming Manual](/assets/doc/pm0214-stm32-cortexm4-mcus-and-mpus-programming-manual-stmicroelectronics.pdf)
* [STM32 Nucleo-32 User Manual](/assets/doc/um1956-stm32-nucleo32-boards-mb1180-stmicroelectronics.pdf)
* [Cortex-M4 Technical Reference Manual](/assets/doc/DDI0439B_cortex_m4_r0p0.pdf)
* [ARMv7-M Architecture Reference Manual](/assets/doc/DDI0403E_B_armv7m_arm.pdf)

# UPduino v3.1 & iCE40 UP5K Documentation
* [iCE40 UltraPlus Family Data Sheet](/assets/doc/FPGA-DS-02008-2-0-iCE40-UltraPlus-Family-Data-Sheet.pdf)
* [iCE40 Oscillator Usage Guide](/assets/doc/FPGA-TN-02008-1-7-iCE40-Oscillator-Usage-Guide.pdf)
* [iCE40 SPRAM Usage Guide](/assets/doc/FPGA-TN-02022-1-3-iCE40-SPRAM-Usage-Guide.pdf)
* [iCE40 Technology Library](/assets/doc/FPGA-TN-02026-3-2-iCE40-Technology-Library.pdf)
  * [Note on translating from iCEcube2 naming to Radiant](/assets/doc/Radiant20_migration_icecube2.pdf)
* [UPduino Documentation](https://upduino.readthedocs.io/en/latest/index.html#)
  * [UPduino v3.1 Pinout](https://upduino.readthedocs.io/en/latest/features/specs.html#upduino-pinout)
  * [UPduino v3.1 Schematic](/assets/doc/UPduino_v3.0.pdf)

## Open Source Toolchain for iCE40
* [apio](https://apiodoc.readthedocs.io)
* [Project IceStorm](http://bygone.clairexen.net/icestorm/)
* [OSS CAD Suite](https://github.com/YosysHQ)
* [Shawn Hymel Introduction to FPGA YouTube Series](https://www.youtube.com/watch?v=lLg1AgA2Xoo&list=PLEBQazB0HUyT1WmMONxRZn9NmQ_9CIKhb)

# Embedded Systems Related Newsletters
* [The Embedded Muse](http://www.ganssle.com/tem-subunsub.html)
* [Embedded Systems Weekly](https://embedsysweekly.com)

# SystemVerilog Resources
* [Synthesizing SystemVerilog: Busting the Myth that SystemVerilog is only for Verification](https://sutherland-hdl.com/papers/2013-SNUG-SV_Synthesizable-SystemVerilog_paper.pdf)
* [IEEE Standard for SystemVerilog (IEEE Std 1800-2017)](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8299595)

# C Programming
* [Appendix C from Digital Design and Computer Architecture: ARM Edition](http://pages.hmc.edu/harris/class/e85/old/fall21/12_AppC_Online.pdf)

# ARM Assembly Quick Reference Cards
* [ARM® and Thumb®-2 Instruction Set Quick Reference Card](/assets/doc/QRC0001_UAL.pdf)
* [Thumb® 16-bit Instruction Set Quick Reference Card](/assets/doc/QRC0006_UAL16.pdf)

# Textbook Resources
* [DDCA ARMed: Ch 9. I/O Systems](http://pages.hmc.edu/harris/class/e155/09_Ch%2009_online.pdf)

# General Resources
* [Adafruit Guide to Excellent Soldering](https://learn.adafruit.com/adafruit-guide-excellent-soldering/common-problems)
* [Guidelines for Drawing Schematics](https://www.k-state.edu/edl/docs/pubs/technical-resources/Technote8.pdf)

# Part Datasheets
* [Understanding and Interpreting Standard-Logic Data Sheets](https://www.ti.com/lit/an/szza036c/szza036c.pdf) is a helpful Application Report from Texas Instruments which provides explanations about the information on a standard logic chip data sheet.
* [LM386 Datasheet](https://www.ti.com/lit/ds/symlink/lm386.pdf)  
* [MCP4801 Datasheet](https://ww1.microchip.com/downloads/en/DeviceDoc/22244B.pdf)
* [2N3906 PNP Transistor Datasheet](/assets/doc/2N3906-D.pdf)
* [MAN6410 Common Anode Seven-segment Display Datasheet](/assets/doc/MAN64x0 Series.pdf)
* [Adafruit 3x4 Keypad Pinout](/assets/doc/Keypad_Pinout_Adafruit_3845.jpg)

# Helpful Web Links

## Past versions of E155
* [FA19](http://pages.hmc.edu/harris/class/e155/)
* [FA20](http://pages.hmc.edu/brake/class/e155/fa20)
* [FA21](http://pages.hmc.edu/brake/class/e155/fa21)
* [FA22](http://pages.hmc.edu/brake/class/e155/fa22)

# Textbook Links
* [Digital Design and Computer Architecture](https://ccl.on.worldcat.org/oclc/900028206)
* [The Definitive Guide to ARM® Cortex®-M3 and Cortex®-M4 Processors](https://ccl.on.worldcat.org/oclc/868231734)
* [O’Reilly Safari Learning Platform: Academic edition](https://libguides.libraries.claremont.edu/662)
  * [Expert C Programming](https://learning.oreilly.com/library/view/expert-c-programming/0131774298/)

# Vendors
* [SparkFun](http://www.sparkfun.com/)
* [Adafruit](http://www.adafruit.com/)
* [Digikey](http://www.digikey.com/)
* [Mouser](http://www.mouser.com/)
